{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:openstack:python-keystoneclient:0.2.2:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:openstack:python-keystoneclient:0.2.3:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:openstack:python-keystoneclient:0.2.4:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:openstack:python-keystoneclient:0.3.0:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:openstack:python-keystoneclient:0.3.1:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:openstack:python-keystoneclient:0.3.2:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:openstack:python-keystoneclient:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "0.4.2",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2014-0105"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "product": {
              "product_data": [
                {
                  "product_name": "python-keystoneclient",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "=",
                        "version_value": "0.2.2"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.2.3"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.2.4"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.3.0"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.3.1"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.3.2"
                      },
                      {
                        "version_affected": "\u003c=",
                        "version_value": "0.4.2"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "openstack"
          }
        ]
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The auth_token middleware in the OpenStack Python client library for Keystone (aka python-keystoneclient) before 0.7.0 does not properly retrieve user tokens from memcache, which allows remote authenticated users to gain privileges in opportunistic circumstances via a large number of requests, related to an \"interaction between eventlet and python-memcached.\""
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-255"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "RHSA-2014:0382",
          "refsource": "REDHAT",
          "tags": [],
          "url": "http://rhn.redhat.com/errata/RHSA-2014-0382.html"
        },
        {
          "name": "RHSA-2014:0409",
          "refsource": "REDHAT",
          "tags": [],
          "url": "http://rhn.redhat.com/errata/RHSA-2014-0409.html"
        },
        {
          "name": "[oss-security] 20140327 [OSSA 2014-007] Potential context confusion in Keystone middleware  (CVE-2014-0105)",
          "refsource": "MLIST",
          "tags": [
            "Patch"
          ],
          "url": "http://www.openwall.com/lists/oss-security/2014/03/27/4"
        },
        {
          "name": "https://bugs.launchpad.net/python-keystoneclient/+bug/1282865",
          "refsource": "CONFIRM",
          "tags": [
            "Vendor Advisory"
          ],
          "url": "https://bugs.launchpad.net/python-keystoneclient/+bug/1282865"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "accessComplexity": "MEDIUM",
        "accessVector": "NETWORK",
        "authentication": "SINGLE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 6,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "vectorString": "AV:N/AC:M/Au:S/C:P/I:P/A:P",
        "version": "2.0"
      },
      "exploitabilityScore": 6.8,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": false
    }
  },
  "lastModifiedDate": "2017-12-16T02:29Z",
  "publishedDate": "2014-04-15T14:55Z"
}