{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:ibm:lotus_mobile_connect:6.1.1:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:ibm:lotus_mobile_connect:6.1.1.1:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:ibm:lotus_mobile_connect:6.1.2:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:ibm:lotus_mobile_connect:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "6.1.3",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2010-4593"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "product": {
              "product_data": [
                {
                  "product_name": "lotus_mobile_connect",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "=",
                        "version_value": "6.1.1"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "6.1.1.1"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "6.1.2"
                      },
                      {
                        "version_affected": "\u003c=",
                        "version_value": "6.1.3"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "ibm"
          }
        ]
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The Connection Manager in IBM Lotus Mobile Connect before 6.1.4 does not properly maintain a certain reference count, which allows remote authenticated users to cause a denial of service (IP address exhaustion) by making invalid attempts to establish sessions with the same VPN ID from multiple devices."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-399"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "42703",
          "refsource": "SECUNIA",
          "tags": [],
          "url": "http://secunia.com/advisories/42703"
        },
        {
          "name": "IZ75012",
          "refsource": "AIXAPAR",
          "tags": [],
          "url": "http://www-01.ibm.com/support/docview.wss?uid=swg1IZ75012"
        },
        {
          "name": "http://www-01.ibm.com/support/docview.wss?uid=swg27020327",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "http://www-01.ibm.com/support/docview.wss?uid=swg27020327"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "accessComplexity": "LOW",
        "accessVector": "NETWORK",
        "authentication": "SINGLE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 4,
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "vectorString": "AV:N/AC:L/Au:S/C:N/I:N/A:P",
        "version": "2.0"
      },
      "exploitabilityScore": 8,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": false
    }
  },
  "lastModifiedDate": "2011-01-11T06:46Z",
  "publishedDate": "2010-12-22T21:00Z"
}