{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:ibm:cloud_private:3.1.1:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:ibm:cloud_private:3.1.2:*:*:*:*:*:*:*",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2019-4415"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "product": {
              "product_data": [
                {
                  "product_name": "cloud_private",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "=",
                        "version_value": "3.1.1"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "3.1.2"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "ibm"
          }
        ]
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM Cloud Private 3.1.1 and 3.1.2 could allow a local user to obtain elevated privileges due to improper security context constraints. IBM X-Force ID: 162706."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-264"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "http://www.ibm.com/support/docview.wss?uid=ibm10887857",
          "refsource": "CONFIRM",
          "tags": [
            "Vendor Advisory"
          ],
          "url": "http://www.ibm.com/support/docview.wss?uid=ibm10887857"
        },
        {
          "name": "ibm-cloud-cve20194415-priv-escalation (162706)",
          "refsource": "XF",
          "tags": [
            "VDB Entry"
          ],
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/162706"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "acInsufInfo": false,
      "cvssV2": {
        "accessComplexity": "LOW",
        "accessVector": "LOCAL",
        "authentication": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 4.6,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "vectorString": "AV:L/AC:L/Au:N/C:P/I:P/A:P",
        "version": "2.0"
      },
      "exploitabilityScore": 3.9,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": false
    },
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "LOCAL",
        "availabilityImpact": "HIGH",
        "baseScore": 7.8,
        "baseSeverity": "HIGH",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "HIGH",
        "privilegesRequired": "LOW",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        "version": "3.0"
      },
      "exploitabilityScore": 1.8,
      "impactScore": 5.9
    }
  },
  "lastModifiedDate": "2019-07-26T13:54Z",
  "publishedDate": "2019-07-25T15:15Z"
}