{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:ipython:notebook:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "3.2.1",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      },
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:jupyter:notebook:4.0.0:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:jupyter:notebook:4.0.1:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:jupyter:notebook:4.0.2:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:jupyter:notebook:4.0.3:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:jupyter:notebook:4.0.4:*:*:*:*:*:*:*",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2015-7337"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "product": {
              "product_data": [
                {
                  "product_name": "notebook",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "\u003c=",
                        "version_value": "3.2.1"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "ipython"
          },
          {
            "product": {
              "product_data": [
                {
                  "product_name": "notebook",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "=",
                        "version_value": "4.0.0"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "4.0.1"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "4.0.2"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "4.0.3"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "4.0.4"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "jupyter"
          }
        ]
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The editor in IPython Notebook before 3.2.2 and Jupyter Notebook 4.0.x before 4.0.5 allows remote attackers to execute arbitrary JavaScript code via a crafted file, which triggers a redirect to files/, related to MIME types."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-20"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "FEDORA-2015-16128",
          "refsource": "FEDORA",
          "tags": [],
          "url": "http://lists.fedoraproject.org/pipermail/package-announce/2015-September/167670.html"
        },
        {
          "name": "[oss-security] 20150916 CVE Request: Maliciously crafted text files in IPython/Jupyter editor",
          "refsource": "MLIST",
          "tags": [],
          "url": "http://seclists.org/oss-sec/2015/q3/558"
        },
        {
          "name": "[oss-security] 20150924 Re: CVE Request: Maliciously crafted text files in IPython/Jupyter editor",
          "refsource": "MLIST",
          "tags": [],
          "url": "http://seclists.org/oss-sec/2015/q3/634"
        },
        {
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1264067",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1264067"
        },
        {
          "name": "https://github.com/ipython/ipython/commit/0a8096adf165e2465550bd5893d7e352544e5967",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://github.com/ipython/ipython/commit/0a8096adf165e2465550bd5893d7e352544e5967"
        },
        {
          "name": "https://github.com/jupyter/notebook/commit/9e63dd89b603dfbe3a7e774d8a962ee0fa30c0b5",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://github.com/jupyter/notebook/commit/9e63dd89b603dfbe3a7e774d8a962ee0fa30c0b5"
        },
        {
          "name": "GLSA-201512-02",
          "refsource": "GENTOO",
          "tags": [],
          "url": "https://security.gentoo.org/glsa/201512-02"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "accessComplexity": "MEDIUM",
        "accessVector": "NETWORK",
        "authentication": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 6.8,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "vectorString": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
        "version": "2.0"
      },
      "exploitabilityScore": 8.6,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": true
    }
  },
  "lastModifiedDate": "2016-12-07T18:23Z",
  "publishedDate": "2015-09-29T19:59Z"
}