{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:python:python:3.1:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:python:3.1.1:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:python:3.1.2:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:python:3.1.5:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:python:3.2:alpha:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:python:3.2.3:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:python:3.2.2150:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:python:3.3:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:python:3.3:beta2:*:*:*:*:*:*",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2012-2135"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "product": {
              "product_data": [
                {
                  "product_name": "python",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "=",
                        "version_value": "3.1"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "3.1.1"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "3.1.2"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "3.1.5"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "3.2"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "3.2.3"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "3.2.2150"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "3.3"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "python"
          }
        ]
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "NVD-CWE-Other"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389",
          "refsource": "MISC",
          "tags": [],
          "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389"
        },
        {
          "name": "http://bugs.python.org/issue14579",
          "refsource": "MISC",
          "tags": [
            "Vendor Advisory"
          ],
          "url": "http://bugs.python.org/issue14579"
        },
        {
          "name": "51087",
          "refsource": "SECUNIA",
          "tags": [],
          "url": "http://secunia.com/advisories/51087"
        },
        {
          "name": "51089",
          "refsource": "SECUNIA",
          "tags": [],
          "url": "http://secunia.com/advisories/51089"
        },
        {
          "name": "[oss-security] 20120425 CVE Request: Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler aligned_end is not updated",
          "refsource": "MLIST",
          "tags": [],
          "url": "http://www.openwall.com/lists/oss-security/2012/04/25/2"
        },
        {
          "name": "[oss-security] 20120425 Re: CVE Request: Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler aligned_end is not updated",
          "refsource": "MLIST",
          "tags": [],
          "url": "http://www.openwall.com/lists/oss-security/2012/04/25/4"
        },
        {
          "name": "USN-1615-1",
          "refsource": "UBUNTU",
          "tags": [],
          "url": "http://www.ubuntu.com/usn/USN-1615-1"
        },
        {
          "name": "USN-1616-1",
          "refsource": "UBUNTU",
          "tags": [],
          "url": "http://www.ubuntu.com/usn/USN-1616-1"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "accessComplexity": "LOW",
        "accessVector": "NETWORK",
        "authentication": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 6.4,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "vectorString": "AV:N/AC:L/Au:N/C:P/I:N/A:P",
        "version": "2.0"
      },
      "exploitabilityScore": 10,
      "impactScore": 4.9,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": false
    }
  },
  "lastModifiedDate": "2013-05-15T03:25Z",
  "publishedDate": "2012-08-14T22:55Z"
}